# This file is autogenerated **DO NOT EDIT DIRECTLY**
# Tool @file:bin/generate-ignores.js combines
# - @file:.config/filelists/ai.ignorefile.md
# - @file:.config/filelists/ai.ignorefile
# - @file:.config/filelists/garbage.ignorefile
# - @file:.config/filelists/security.ignorefile
